lets watch the failures

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,13 +27,13 @@ commands:
           # Add when this will run
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS = curl https://kvdb.io/9tDAL53faqACSAjQTsGwmN/migration_${CIRCLE_WORKFLOW_ID:0:7}
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd ~/project/backend
+              npm install
+              cd backend
+              npm run migrations:revert
             fi
 
 jobs:
@@ -238,6 +238,117 @@ jobs:
       # Here's where you will add some code to rollback on failure      
       - destroy-environment
 
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            cd backend &&
+            npm install &&
+            # Run and save the migration output
+            npm run migrations > migrations_dump.txt
+            # exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+                # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+                # curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                curl https://kvdb.io/9tDAL53faqACSAjQTsGwmN/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+            # Here's where you will add some code to rollback on failure
+
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - aws-cli/setup:
+          aws-access-key-id: AWS_ACCESS_KEY_ID
+          aws-region: US_EAST_1_REGION
+          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible &&
+            yum install -y tar gzip &&
+            yum install python3
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name = tag:Name,Values = backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --region us-east-1 \
+              --output text ) &&
+            export API_URL="http://${BACKEND_IP}:3030" &&
+            echo "API_URL = ${API_URL}" &&
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env &&
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend &&
+            npm install &&
+            npm run build &&
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist &&
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive &&
+          # Here's where you will add some code to rollback on failure 
+      - destroy-environment
+      - revert-migrations     
+                    
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: alpine:latest
+    steps:
+      # Checkout code from git
+      - checkout
+      - aws-cli/setup:
+          aws-access-key-id: AWS_ACCESS_KEY_ID
+          aws-region: US_EAST_1_REGION
+          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          # You can get this ID in the section where you registered the SSH Key
+          fingerprints: "53:d6:66:21:ae:92:ca:dc:ff:a0:ea:1f:40:8c:07:94"      
+      # attach workspace
+      - attach_workspace:
+          at: ~/project/.circleci/ansible/inventory.txt
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible &&
+            yum install -y tar gzip &&
+            yum install nodejs &&
+            yum install npm
+      - run:
+          name: Deploy backend
+          command: |
+            cd backend &&
+            npm i &&
+            npm run build &&
+            cd .. &&
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz . &&
+            cd .circleci/ansible &&
+            echo "Contents  of the inventory.txt file is -------" &&
+            cat inventory.txt &&
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment
+      - revert-migration  
+
+
 
 workflows:
   default:
@@ -253,4 +364,4 @@ workflows:
       # - scan-frontend:
       #     requires: [build-frontend]
       - deploy-infrastructure
-          # requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          #requires: [test-frontend, test-backend, scan-frontend, scan-backend]
